### ISSUE TITLE
Google and Facebook Auth Buttons

### ISSUE THREAD

**Issue by Adarshg315** [Adarshg315/e-tribal#11]
@apoorvverma - Facebook Button
@Arya23sharma - Google Button

Add auth button anywhere on the Dashboard

**Comment by Arya23sharma** [comment]
ohk

**Comment by Adarshg315** [comment]
@apoorvverma  arya is half way to the issue what are you doing till now???

**Comment by Adarshg315** [comment]
we will see this later
