### ISSUE TITLE
change mode on shopkeeper's dashboard 

### ISSUE THREAD

**Issue by Arya23sharma** [Adarshg315/e-tribal#19]
change the mode light to dark

**Comment by bhavin-a** [comment]
Hi @Adarshg315 @Arya23sharma 

Can you please elaborate on this more? Have worked on some React projects before, so I think would be able to help with a bit more details. Thanks!

**Comment by Adarshg315** [comment]
> Hi @Adarshg315 @Arya23sharma
> 
> Can you please elaborate on this more? Have worked on some React projects before, so I think would be able to help with a bit more details. Thanks!

**Comment by Adarshg315** [comment]
@Bhavin789  this is the dark and light mode functionality we were looking for on the web and mobile devices both
