### ISSUE TITLE
wishlist button 

### ISSUE THREAD

**Issue by Adarshg315** [Adarshg315/e-tribal#2]
whishlist button functionality @Arya23sharma

**Comment by Arya23sharma** [comment]
ohk

**Comment by Adarshg315** [comment]
Apoorv help Arya

**Comment by Adarshg315** [comment]
@apoorvverma  don't just help you both have to complete this task together

**Comment by apoorvverma** [comment]
Done!!

**Comment by Adarshg315** [comment]
@apoorvverma don't close the issue without my review reopen it and ask me for the review I will only close it because I have created it
